version: "3"

services:

  frontend:
    build: ./front-end
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app

  backend:
    build: ./back-end
    ports:
      - "8000:8000"
    volumes:
      - ./back-end:/app