version: "3"

services:

  # frontend:
  #   # image: node:18
  #   build: ./front-end
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./front-end:/app
    # environment:
    #   - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./back-end
    ports:
      - "8000:8000"
    volumes:
      - ./back-end:/app
    # environment:
    #   - CHOKIDAR_USEPOLLING=tru